### ISSUE TITLE
In regards to: Missing Webpage Functionality, Issue #9

### ISSUE THREAD

**Issue by budpi** [alaudet/raspi-sump#19]
You stated that "Those graphs are uploaded to an offsite webserver and have some programming behind them to display monthly graphs."

What steps are needed to achieve the same functionality? Is this a self-hosted webserver or a service that you have purchased and how advanced is the programming? And, asked with all due respect, what was the reason for not including it in the final project?

Thanks so much, keep up the great work..

**Comment by alaudet** [comment]
I had hoped at some point to add the functionality but in the end just provided something that can allow you to access past graphs.  What you see on my website is self hosted.  It is not a complicated program but isn't something I feel comfortable releasing.  It's an ugly hack that requires some steps to setup the webserver properly.  I have only dabbled in web stuff and don't really feel comfortable releasing something like that.

To  achieve the same functionality all that is needed is a web host, transferring your graphs to the offsite webserver (ftp or sftp), parsing the folder and presenting the graphs on a webpage.  You can use any programming language to do that, Python with a lightweight web framework like flask.  php or perl would also work fine. 

There are so many different, varied webhosts, this is the reason I did not include it in raspisump.  The purpose of the program is to monitor my sump pit, the rest is eye candy :-).  I had considered even offering the hosting service for a nominal fee but that brings with it all the support and time required, which as a hobbyist doesn't really interest me.

That being said, if someone were willing to develop a nice front end for raspisump I would consider including it in the package if it met certain conditions.  Otherwise nothing prevents someone from forking my app and building and releasing something better.  That is why I have licensed it under the MIT license which allows someone to take this code and make something better without restrictions.

Hope this answers your question.
