### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by sjmorrow26990** [alaudet/raspi-sump#20]
Hi
Here is a cut and paste of the error message i'm getting, sorry if it is a stupid error that I caused but the is a great project and my FIRST build on a pi.  The rsump.py file gives me this error when I run it, What can I do to fix it.

Thanks Stan

Traceback (most recent call last):
  File "/usr/local/bin/rsump.py", line 27, in <module>
    reading.water_depth()
  File "/usr/local/lib/python3.4/dist-packages/raspisump/reading.py", line 68, in water_depth
    log.log_reading(water_depth)
  File "/usr/local/lib/python3.4/dist-packages/raspisump/log.py", line 19, in log_reading
    csv_file = open(filename, 'a')
PermissionError: [Errno 13] Permission denied: '/home/pi/raspi-sump/csv/waterlevel-20170311.csv'

**Comment by alaudet** [comment]
It's a permissions error on the csv file.  I would need to know what permissions you have on the file.  
Are you running rsump.py with sudo?  You shouldn't have to but if the file was created as root and then you are trying to run it as a regular user then it could be the problem.

What is the output of   ls -al /home/pi/raspi-sump/csv/

This will list all files  in the folder and show the permissions on them.

**Comment by sjmorrow26990** [comment]
Hi
can you point in the right direction on how to fix this error.  this is the message i get when i run rsumpchart.py,  


pi@sump:~/raspi-sump $ rsumpchart.py
Traceback (most recent call last):
  File "/usr/local/bin/rsumpchart.py", line 24, in <module>
    main()
  File "/usr/local/bin/rsumpchart.py", line 21, in main
    todaychart.graph(csv_file, filename, bytes2str)
  File "/usr/local/lib/python3.4/dist-packages/raspisump/todaychart.py", line 52, in graph
    converters={0: bytes2str}
  File "/usr/lib/python3/dist-packages/numpy/lib/npyio.py", line 736, in loadtxt
    fh = iter(open(fname))
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/raspi-sump/csv/waterlevel-20170318.csv'

**Comment by alaudet** [comment]
Does this file exist on your pi?

'/home/pi/raspi-sump/csv/waterlevel-20170318.csv'

**Comment by sjmorrow26990** [comment]
Sorry I should have mentation  that there is no files in the folder, I have tried runny rsump.py, than rsumpchart.py , than resumpwebchart.py.  rsump.py works but the next two give me that error.

thanks

**Comment by alaudet** [comment]
Then that is the problem.   The error message is saying exactly that.  The next thing to check is what happens when you try to run the rsump.py program manually.  Are you still getting that permission denied error?

What are the permissions on your csv folder?  Send me the output of 'ls -al /home/pi/raspi-sump/csv'

**Comment by sjmorrow26990** [comment]
Thanks for getting back to me....

I chmod the csv folder to 775 and than 777 but still getting the same error.

Here is the outputs

pi@sump:~/raspi-sump $ chmod 775 csv
pi@sump:~ $ rsumpchart.py
Traceback (most recent call last):
  File "/usr/local/bin/rsumpchart.py", line 24, in <module>
    main()
  File "/usr/local/bin/rsumpchart.py", line 21, in main
    todaychart.graph(csv_file, filename, bytes2str)
  File "/usr/local/lib/python3.4/dist-packages/raspisump/todaychart.py", line 52                        , in graph
    converters={0: bytes2str}
  File "/usr/lib/python3/dist-packages/numpy/lib/npyio.py", line 736, in loadtxt
    fh = iter(open(fname))
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/raspi-sump/csv                        /waterlevel-20170319.csv'


pi@sump:~ $ cd raspi-sump
pi@sump:~/raspi-sump $ ls -la
total 48
drwxr-xr-x  9 pi   root 4096 Mar 18 14:21 .
drwxr-xr-x 18 pi   pi   4096 Mar 18 14:44 ..
drwxr-xr-x  3 pi   root 4096 Mar 18 14:42 charts
drwxr-xr-x  2 pi   root 4096 Mar 18 14:10 cron
-rw-r--r--  1 root root  132 Mar 18 14:42 crontab
drwxrwxr-x  2 pi   root 4096 Mar 18 14:10 csv
drwxr-xr-x  2 pi   root 4096 Mar 18 14:10 docs
drwxr-xr-x  2 pi   root 4096 Mar 18 15:04 logs
-rw-r--r--  1 pi   root 5051 Mar 18 15:07 raspisump.conf
drwxr-xr-x  2 pi   root 4096 Mar 18 14:11 sample_config
drwxr-xr-x  4 pi   root 4096 Mar 18 14:10 web


pi@sump:~/raspi-sump $ chmod 777 csv
pi@sump:~/raspi-sump $ ls -la
total 48
drwxr-xr-x  9 pi   root 4096 Mar 18 14:21 .
drwxr-xr-x 18 pi   pi   4096 Mar 18 14:44 ..
drwxr-xr-x  3 pi   root 4096 Mar 18 14:42 charts
drwxr-xr-x  2 pi   root 4096 Mar 18 14:10 cron
-rw-r--r--  1 root root  132 Mar 18 14:42 crontab
drwxrwxrwx  2 pi   root 4096 Mar 18 14:10 csv
drwxr-xr-x  2 pi   root 4096 Mar 18 14:10 docs
drwxr-xr-x  2 pi   root 4096 Mar 18 15:04 logs
-rw-r--r--  1 pi   root 5051 Mar 18 15:07 raspisump.conf
drwxr-xr-x  2 pi   root 4096 Mar 18 14:11 sample_config
drwxr-xr-x  4 pi   root 4096 Mar 18 14:10 web

pi@sump:~/raspi-sump $ rsumpchart.py
Traceback (most recent call last):
  File "/usr/local/bin/rsumpchart.py", line 24, in <module>
    main()
  File "/usr/local/bin/rsumpchart.py", line 21, in main
    todaychart.graph(csv_file, filename, bytes2str)
  File "/usr/local/lib/python3.4/dist-packages/raspisump/todaychart.py", line 52                        , in graph
    converters={0: bytes2str}
  File "/usr/lib/python3/dist-packages/numpy/lib/npyio.py", line 736, in loadtxt
    fh = iter(open(fname))
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/raspi-sump/csv                        /waterlevel-20170319.csv'

pi@sump:~/raspi-sump $ cd csv
pi@sump:~/raspi-sump/csv $ ls
README.md
pi@sump:~/raspi-sump/csv $

**Comment by alaudet** [comment]
You need to run rsump.py first to create the csv file. Rsumpchart.py is looking for it but it doesn't exist.                                                                                                                                                                                                                                                                                                                                        Al                                                                                                                                                                                                                From: sjmorrow26990Sent: Sunday, March 19, 2017 10:02 AMTo: alaudet/raspi-sumpReply To: alaudet/raspi-sumpCc: Al Audet; CommentSubject: Re: [alaudet/raspi-sump] Error Message (#20)Thanks for getting back to me....
I chmod the csv folder to 775 and than 777 but still getting the same error.
Here is the outputs
pi@sump:/raspi-sump $ chmod 775 csv
pi@sump: $ rsumpchart.py
Traceback (most recent call last):
File "/usr/local/bin/rsumpchart.py", line 24, in 
main()
File "/usr/local/bin/rsumpchart.py", line 21, in main
todaychart.graph(csv_file, filename, bytes2str)
File "/usr/local/lib/python3.4/dist-packages/raspisump/todaychart.py", line 52                        , in graph
converters={0: bytes2str}
File "/usr/lib/python3/dist-packages/numpy/lib/npyio.py", line 736, in loadtxt
fh = iter(open(fname))
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/raspi-sump/csv                        /waterlevel-20170319.csv'
pi@sump:~ $ cd raspi-sump
pi@sump:~/raspi-sump $ ls -la
total 48
drwxr-xr-x  9 pi   root 4096 Mar 18 14:21 .
drwxr-xr-x 18 pi   pi   4096 Mar 18 14:44 ..
drwxr-xr-x  3 pi   root 4096 Mar 18 14:42 charts
drwxr-xr-x  2 pi   root 4096 Mar 18 14:10 cron
-rw-r--r--  1 root root  132 Mar 18 14:42 crontab
drwxrwxr-x  2 pi   root 4096 Mar 18 14:10 csv
drwxr-xr-x  2 pi   root 4096 Mar 18 14:10 docs
drwxr-xr-x  2 pi   root 4096 Mar 18 15:04 logs
-rw-r--r--  1 pi   root 5051 Mar 18 15:07 raspisump.conf
drwxr-xr-x  2 pi   root 4096 Mar 18 14:11 sample_config
drwxr-xr-x  4 pi   root 4096 Mar 18 14:10 web
pi@sump:/raspi-sump $ chmod 777 csv
pi@sump:/raspi-sump $ ls -la
total 48
drwxr-xr-x  9 pi   root 4096 Mar 18 14:21 .
drwxr-xr-x 18 pi   pi   4096 Mar 18 14:44 ..
drwxr-xr-x  3 pi   root 4096 Mar 18 14:42 charts
drwxr-xr-x  2 pi   root 4096 Mar 18 14:10 cron
-rw-r--r--  1 root root  132 Mar 18 14:42 crontab
drwxrwxrwx  2 pi   root 4096 Mar 18 14:10 csv
drwxr-xr-x  2 pi   root 4096 Mar 18 14:10 docs
drwxr-xr-x  2 pi   root 4096 Mar 18 15:04 logs
-rw-r--r--  1 pi   root 5051 Mar 18 15:07 raspisump.conf
drwxr-xr-x  2 pi   root 4096 Mar 18 14:11 sample_config
drwxr-xr-x  4 pi   root 4096 Mar 18 14:10 web
pi@sump:~/raspi-sump $ rsumpchart.py
Traceback (most recent call last):
File "/usr/local/bin/rsumpchart.py", line 24, in 
main()
File "/usr/local/bin/rsumpchart.py", line 21, in main
todaychart.graph(csv_file, filename, bytes2str)
File "/usr/local/lib/python3.4/dist-packages/raspisump/todaychart.py", line 52                        , in graph
converters={0: bytes2str}
File "/usr/lib/python3/dist-packages/numpy/lib/npyio.py", line 736, in loadtxt
fh = iter(open(fname))
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/raspi-sump/csv                        /waterlevel-20170319.csv'
pi@sump:/raspi-sump $ cd csv
pi@sump:/raspi-sump/csv $ ls
README.md
pi@sump:~/raspi-sump/csv $

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/alaudet/raspi-sump","title":"alaudet/raspi-sump","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/alaudet/raspi-sump"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sjmorrow26990 in #20: Thanks for getting back to me....\r\n\r\nI chmod the csv folder to 775 and than 777 but still getting the same error.\r\n\r\nHere is the outputs\r\n\r\npi@sump:~/raspi-sump $ chmod 775 csv\r\npi@sump:~ $ rsumpchart.py\r\nTraceback (most recent call last):\r\n  File \"/usr/local/bin/rsumpchart.py\", line 24, in \u003cmodule\u003e\r\n    main()\r\n  File \"/usr/local/bin/rsumpchart.py\", line 21, in main\r\n    todaychart.graph(csv_file, filename, bytes2str)\r\n  File \"/usr/local/lib/python3.4/dist-packages/raspisump/todaychart.py\", line 52                        , in graph\r\n    converters={0: bytes2str}\r\n  File \"/usr/lib/python3/dist-packages/numpy/lib/npyio.py\", line 736, in loadtxt\r\n    fh = iter(open(fname))\r\nFileNotFoundError: [Errno 2] No such file or directory: '/home/pi/raspi-sump/csv                        /waterlevel-20170319.csv'\r\n\r\n\r\npi@sump:~ $ cd raspi-sump\r\npi@sump:~/raspi-sump $ ls -la\r\ntotal 48\r\ndrwxr-xr-x  9 pi   root 4096 Mar 18 14:21 .\r\ndrwxr-xr-x 18 pi   pi   4096 Mar 18 14:44 ..\r\ndrwxr-xr-x  3 pi   root 4096 Mar 18 14:42 charts\r\ndrwxr-xr-x  2 pi   root 4096 Mar 18 14:10 cron\r\n-rw-r--r--  1 root root  132 Mar 18 14:42 crontab\r\ndrwxrwxr-x  2 pi   root 4096 Mar 18 14:10 csv\r\ndrwxr-xr-x  2 pi   root 4096 Mar 18 14:10 docs\r\ndrwxr-xr-x  2 pi   root 4096 Mar 18 15:04 logs\r\n-rw-r--r--  1 pi   root 5051 Mar 18 15:07 raspisump.conf\r\ndrwxr-xr-x  2 pi   root 4096 Mar 18 14:11 sample_config\r\ndrwxr-xr-x  4 pi   root 4096 Mar 18 14:10 web\r\n\r\n\r\npi@sump:~/raspi-sump $ chmod 777 csv\r\npi@sump:~/raspi-sump $ ls -la\r\ntotal 48\r\ndrwxr-xr-x  9 pi   root 4096 Mar 18 14:21 .\r\ndrwxr-xr-x 18 pi   pi   4096 Mar 18 14:44 ..\r\ndrwxr-xr-x  3 pi   root 4096 Mar 18 14:42 charts\r\ndrwxr-xr-x  2 pi   root 4096 Mar 18 14:10 cron\r\n-rw-r--r--  1 root root  132 Mar 18 14:42 crontab\r\ndrwxrwxrwx  2 pi   root 4096 Mar 18 14:10 csv\r\ndrwxr-xr-x  2 pi   root 4096 Mar 18 14:10 docs\r\ndrwxr-xr-x  2 pi   root 4096 Mar 18 15:04 logs\r\n-rw-r--r--  1 pi   root 5051 Mar 18 15:07 raspisump.conf\r\ndrwxr-xr-x  2 pi   root 4096 Mar 18 14:11 sample_config\r\ndrwxr-xr-x  4 pi   root 4096 Mar 18 14:10 web\r\n\r\npi@sump:~/raspi-sump $ rsumpchart.py\r\nTraceback (most recent call last):\r\n  File \"/usr/local/bin/rsumpchart.py\", line 24, in \u003cmodule\u003e\r\n    main()\r\n  File \"/usr/local/bin/rsumpchart.py\", line 21, in main\r\n    todaychart.graph(csv_file, filename, bytes2str)\r\n  File \"/usr/local/lib/python3.4/dist-packages/raspisump/todaychart.py\", line 52                        , in graph\r\n    converters={0: bytes2str}\r\n  File \"/usr/lib/python3/dist-packages/numpy/lib/npyio.py\", line 736, in loadtxt\r\n    fh = iter(open(fname))\r\nFileNotFoundError: [Errno 2] No such file or directory: '/home/pi/raspi-sump/csv                        /waterlevel-20170319.csv'\r\n\r\npi@sump:~/raspi-sump $ cd csv\r\npi@sump:~/raspi-sump/csv $ ls\r\nREADME.md\r\npi@sump:~/raspi-sump/csv $\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/alaudet/raspi-sump/issues/20#issuecomment-287618733"}}}

**Comment by sjmorrow26990** [comment]
ok format the sd card and did a fresh install, and I still have the same issue.......

here is all the code output

pi@192.168.1.126's password:

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sun Mar 19 12:20:33 2017

SSH is enabled and the default password for the 'pi' user has not been changed.
This is a security risk - please login as the 'pi' user and type 'passwd' to set a new password.

pi@sump:~ $ sudo apt-get install python3-pip
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-pip is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@sump:~ $ sudo pip3 install raspisump
Downloading/unpacking raspisump
  Downloading raspisump-1.1.0.tar.gz (69kB): 69kB downloaded
  Running setup.py (path:/tmp/pip-build-og4qe65x/raspisump/setup.py) egg_info for package raspisump

Downloading/unpacking hcsr04sensor (from raspisump)
  Downloading hcsr04sensor-1.5.1.tar.gz
  Running setup.py (path:/tmp/pip-build-og4qe65x/hcsr04sensor/setup.py) egg_info for package hcsr04sensor

Requirement already satisfied (use --upgrade to upgrade): RPi.GPIO in /usr/lib/python3/dist-packages (from hcsr04sensor->raspisump)
Installing collected packages: raspisump, hcsr04sensor
  Running setup.py install for raspisump
    changing mode of build/scripts-3.4/rsump.py from 644 to 755
    changing mode of build/scripts-3.4/rsumpchart.py from 644 to 755
    changing mode of build/scripts-3.4/rsumpmonitor.py from 644 to 755
    changing mode of build/scripts-3.4/rsumpwebchart.py from 644 to 755

    changing mode of /usr/local/bin/rsump.py to 755
    changing mode of /usr/local/bin/rsumpwebchart.py to 755
    changing mode of /usr/local/bin/rsumpchart.py to 755
    changing mode of /usr/local/bin/rsumpmonitor.py to 755
    chmod: cannot access ‘/home/pi/raspi-sump/raspisump.conf’: No such file or directory
  Running setup.py install for hcsr04sensor
    changing mode of build/scripts-3.4/hcsr04.py from 644 to 755

    changing mode of /usr/local/bin/hcsr04.py to 755
Successfully installed raspisump hcsr04sensor
Cleaning up...
pi@sump:~ $ sudo apt-get install python3-matplotlib
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  fonts-lyx libjs-jquery-ui python-matplotlib-data python3-dateutil
  python3-nose python3-pyparsing python3-tz
Suggested packages:
  libjs-jquery-ui-docs dvipng ghostscript inkscape ipython3
  python-matplotlib-doc python3-cairocffi python3-gi-cairo python3-pyqt4
  python3-scipy python3-sip python3-tornado texlive-extra-utils
  texlive-latex-extra ttf-staypuft python-nose-doc
The following NEW packages will be installed:
  fonts-lyx libjs-jquery-ui python-matplotlib-data python3-dateutil
  python3-matplotlib python3-nose python3-pyparsing python3-tz
0 upgraded, 8 newly installed, 0 to remove and 0 not upgraded.
Need to get 7,601 kB of archives.
After this operation, 22.0 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://mirrordirector.raspbian.org/raspbian/ jessie/main fonts-lyx all 2.1.2-2 [176 kB]
Get:2 http://mirrordirector.raspbian.org/raspbian/ jessie/main libjs-jquery-ui all 1.10.1+dfsg-1 [499 kB]
Get:3 http://mirrordirector.raspbian.org/raspbian/ jessie/main python-matplotlib-data all 1.4.2-3.1 [3,041 kB]
Get:4 http://mirrordirector.raspbian.org/raspbian/ jessie/main python3-dateutil all 2.2-2 [33.2 kB]
Get:5 http://mirrordirector.raspbian.org/raspbian/ jessie/main python3-pyparsing all 2.0.3+dfsg1-1 [64.1 kB]
Get:6 http://mirrordirector.raspbian.org/raspbian/ jessie/main python3-tz all 2012c+dfsg-0.1 [25.4 kB]
Get:7 http://mirrordirector.raspbian.org/raspbian/ jessie/main python3-nose all 1.3.4-1 [131 kB]
Get:8 http://mirrordirector.raspbian.org/raspbian/ jessie/main python3-matplotlib armhf 1.4.2-3.1 [3,631 kB]
Fetched 7,601 kB in 11s (639 kB/s)
Selecting previously unselected package fonts-lyx.
(Reading database ... 112361 files and directories currently installed.)
Preparing to unpack .../fonts-lyx_2.1.2-2_all.deb ...
Unpacking fonts-lyx (2.1.2-2) ...
Selecting previously unselected package libjs-jquery-ui.
Preparing to unpack .../libjs-jquery-ui_1.10.1+dfsg-1_all.deb ...
Unpacking libjs-jquery-ui (1.10.1+dfsg-1) ...
Selecting previously unselected package python-matplotlib-data.
Preparing to unpack .../python-matplotlib-data_1.4.2-3.1_all.deb ...
Unpacking python-matplotlib-data (1.4.2-3.1) ...
Selecting previously unselected package python3-dateutil.
Preparing to unpack .../python3-dateutil_2.2-2_all.deb ...
Unpacking python3-dateutil (2.2-2) ...
Selecting previously unselected package python3-pyparsing.
Preparing to unpack .../python3-pyparsing_2.0.3+dfsg1-1_all.deb ...
Unpacking python3-pyparsing (2.0.3+dfsg1-1) ...
Selecting previously unselected package python3-tz.
Preparing to unpack .../python3-tz_2012c+dfsg-0.1_all.deb ...
Unpacking python3-tz (2012c+dfsg-0.1) ...
Selecting previously unselected package python3-nose.
Preparing to unpack .../python3-nose_1.3.4-1_all.deb ...
Unpacking python3-nose (1.3.4-1) ...
Selecting previously unselected package python3-matplotlib.
Preparing to unpack .../python3-matplotlib_1.4.2-3.1_armhf.deb ...
Unpacking python3-matplotlib (1.4.2-3.1) ...
Processing triggers for fontconfig (2.11.0-6.3+deb8u1) ...
Processing triggers for man-db (2.7.0.2-5) ...
Setting up fonts-lyx (2.1.2-2) ...
Setting up libjs-jquery-ui (1.10.1+dfsg-1) ...
Setting up python-matplotlib-data (1.4.2-3.1) ...
Setting up python3-dateutil (2.2-2) ...
Setting up python3-pyparsing (2.0.3+dfsg1-1) ...
Setting up python3-tz (2012c+dfsg-0.1) ...
Setting up python3-nose (1.3.4-1) ...
Setting up python3-matplotlib (1.4.2-3.1) ...
pi@sump:~ $ sudo apt-get install python3-numpy
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-numpy is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@sump:~ $ sudo pip3 install raspisump
Requirement already satisfied (use --upgrade to upgrade): raspisump in /usr/local/lib/python3.4/dist-packages
Requirement already satisfied (use --upgrade to upgrade): hcsr04sensor in /usr/local/lib/python3.4/dist-packages (from raspisump)
Requirement already satisfied (use --upgrade to upgrade): RPi.GPIO in /usr/lib/python3/dist-packages (from hcsr04sensor->raspisump)
Cleaning up...
pi@sump:~ $ cd /home/pi/raspi-sump
pi@sump:~/raspi-sump $ mv sample_config/raspisump.conf .
pi@sump:~/raspi-sump $ sudo nano  /home/pi/raspi-sump/raspisump.conf
pi@sump:~/raspi-sump $ sudo rsump.py
pi@sump:~/raspi-sump $ sudo nano crontab -e
pi@sump:~/raspi-sump $ sudo apt-get install lighttpd
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  libfam0 libterm-readkey-perl libterm-readline-perl-perl spawn-fcgi
Suggested packages:
  fam rrdtool apache2-utils
The following NEW packages will be installed:
  libfam0 libterm-readkey-perl libterm-readline-perl-perl lighttpd spawn-fcgi
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 339 kB of archives.
After this operation, 1,006 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://mirrordirector.raspbian.org/raspbian/ jessie/main libfam0 armhf 2.7.0-17.1 [24.7 kB]
Get:2 http://mirrordirector.raspbian.org/raspbian/ jessie/main libterm-readkey-perl armhf 2.32-1+b2 [26.1 kB]
Get:3 http://mirrordirector.raspbian.org/raspbian/ jessie/main libterm-readline-perl-perl all 1.0303-1 [51.9 kB]
Get:4 http://mirrordirector.raspbian.org/raspbian/ jessie/main lighttpd armhf 1.4.35-4+deb8u1 [222 kB]
Get:5 http://mirrordirector.raspbian.org/raspbian/ jessie/main spawn-fcgi armhf 1.6.4-1 [13.8 kB]
Fetched 339 kB in 1s (230 kB/s)
Selecting previously unselected package libfam0.
(Reading database ... 113287 files and directories currently installed.)
Preparing to unpack .../libfam0_2.7.0-17.1_armhf.deb ...
Unpacking libfam0 (2.7.0-17.1) ...
Selecting previously unselected package libterm-readkey-perl.
Preparing to unpack .../libterm-readkey-perl_2.32-1+b2_armhf.deb ...
Unpacking libterm-readkey-perl (2.32-1+b2) ...
Selecting previously unselected package libterm-readline-perl-perl.
Preparing to unpack .../libterm-readline-perl-perl_1.0303-1_all.deb ...
Unpacking libterm-readline-perl-perl (1.0303-1) ...
Selecting previously unselected package lighttpd.
Preparing to unpack .../lighttpd_1.4.35-4+deb8u1_armhf.deb ...
Unpacking lighttpd (1.4.35-4+deb8u1) ...
Selecting previously unselected package spawn-fcgi.
Preparing to unpack .../spawn-fcgi_1.6.4-1_armhf.deb ...
Unpacking spawn-fcgi (1.6.4-1) ...
Processing triggers for man-db (2.7.0.2-5) ...
Processing triggers for systemd (215-17+deb8u6) ...
Setting up libfam0 (2.7.0-17.1) ...
Setting up libterm-readkey-perl (2.32-1+b2) ...
Setting up libterm-readline-perl-perl (1.0303-1) ...
Setting up lighttpd (1.4.35-4+deb8u1) ...
Setting up spawn-fcgi (1.6.4-1) ...
Processing triggers for libc-bin (2.19-18+deb8u7) ...
Processing triggers for systemd (215-17+deb8u6) ...
pi@sump:~/raspi-sump $ sudo cp /home/pi/raspi-sump/sample_config/lighttpd.conf /etc/lighttpd
pi@sump:~/raspi-sump $ sudo lighttpd-enable-mod dir-listing
Enabling dir-listing: ok
Run /etc/init.d/lighttpd force-reload to enable changes
pi@sump:~/raspi-sump $ sudo /etc/init.d/lighttpd force-reload
[ ok ] Reloading lighttpd configuration (via systemctl): lighttpd.service.
pi@sump:~/raspi-sump $ rsumpwebchart.py
Traceback (most recent call last):
  File "/usr/local/bin/rsumpwebchart.py", line 25, in <module>
    main()
  File "/usr/local/bin/rsumpwebchart.py", line 21, in main
    webchart.create_chart(homedir)
  File "/usr/local/lib/python3.4/dist-packages/raspisump/webchart.py", line 36, in create_chart
    todaychart.graph(csv_file, filename, bytes2str)
  File "/usr/local/lib/python3.4/dist-packages/raspisump/todaychart.py", line 52, in graph
    converters={0: bytes2str}
  File "/usr/lib/python3/dist-packages/numpy/lib/npyio.py", line 736, in loadtxt
    fh = iter(open(fname))
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/raspi-sump/csv/waterlevel-20170319.csv'
pi@sump:~/raspi-sump $ sudo rsump.py
pi@sump:~/raspi-sump $ rsumpwebchart.py
Traceback (most recent call last):
  File "/usr/local/bin/rsumpwebchart.py", line 25, in <module>
    main()
  File "/usr/local/bin/rsumpwebchart.py", line 21, in main
    webchart.create_chart(homedir)
  File "/usr/local/lib/python3.4/dist-packages/raspisump/webchart.py", line 36, in create_chart
    todaychart.graph(csv_file, filename, bytes2str)
  File "/usr/local/lib/python3.4/dist-packages/raspisump/todaychart.py", line 52, in graph
    converters={0: bytes2str}
  File "/usr/lib/python3/dist-packages/numpy/lib/npyio.py", line 736, in loadtxt
    fh = iter(open(fname))
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/raspi-sump/csv/waterlevel-20170319.csv'
pi@sump:~/raspi-sump $ rsumpchart,py
-bash: rsumpchart,py: command not found
pi@sump:~/raspi-sump $ rsumpchart.py
Traceback (most recent call last):
  File "/usr/local/bin/rsumpchart.py", line 24, in <module>
    main()
  File "/usr/local/bin/rsumpchart.py", line 21, in main
    todaychart.graph(csv_file, filename, bytes2str)
  File "/usr/local/lib/python3.4/dist-packages/raspisump/todaychart.py", line 52, in graph
    converters={0: bytes2str}
  File "/usr/lib/python3/dist-packages/numpy/lib/npyio.py", line 736, in loadtxt
    fh = iter(open(fname))
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/raspi-sump/csv/waterlevel-20170319.csv'
pi@sump:~/raspi-sump $ ls -la
total 48
drwxr-xr-x  9 pi   root 4096 Mar 19 12:39 .
drwxr-xr-x 18 pi   pi   4096 Mar 19 12:24 ..
drwxr-xr-x  3 pi   root 4096 Mar 19 12:42 charts
drwxr-xr-x  2 pi   root 4096 Mar 19 12:24 cron
-rw-r--r--  1 root root  138 Mar 19 12:39 crontab
drwxr-xr-x  2 pi   root 4096 Mar 19 12:24 csv
drwxr-xr-x  2 pi   root 4096 Mar 19 12:24 docs
drwxr-xr-x  2 pi   root 4096 Mar 19 12:37 logs
-rw-r--r--  1 pi   root 5032 Mar 19 12:37 raspisump.conf
drwxr-xr-x  2 pi   root 4096 Mar 19 12:32 sample_config
drwxr-xr-x  4 pi   root 4096 Mar 19 12:24 web
pi@sump:~/raspi-sump $ chmod 777 csv
pi@sump:~/raspi-sump $ ls -la
total 48
drwxr-xr-x  9 pi   root 4096 Mar 19 12:39 .
drwxr-xr-x 18 pi   pi   4096 Mar 19 12:24 ..
drwxr-xr-x  3 pi   root 4096 Mar 19 12:42 charts
drwxr-xr-x  2 pi   root 4096 Mar 19 12:24 cron
-rw-r--r--  1 root root  138 Mar 19 12:39 crontab
drwxrwxrwx  2 pi   root 4096 Mar 19 12:24 csv
drwxr-xr-x  2 pi   root 4096 Mar 19 12:24 docs
drwxr-xr-x  2 pi   root 4096 Mar 19 12:37 logs
-rw-r--r--  1 pi   root 5032 Mar 19 12:37 raspisump.conf
drwxr-xr-x  2 pi   root 4096 Mar 19 12:32 sample_config
drwxr-xr-x  4 pi   root 4096 Mar 19 12:24 web
pi@sump:~/raspi-sump $ sudo rsump.py
pi@sump:~/raspi-sump $ rsumpchart.py
Traceback (most recent call last):
  File "/usr/local/bin/rsumpchart.py", line 24, in <module>
    main()
  File "/usr/local/bin/rsumpchart.py", line 21, in main
    todaychart.graph(csv_file, filename, bytes2str)
  File "/usr/local/lib/python3.4/dist-packages/raspisump/todaychart.py", line 52, in graph
    converters={0: bytes2str}
  File "/usr/lib/python3/dist-packages/numpy/lib/npyio.py", line 736, in loadtxt
    fh = iter(open(fname))
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/raspi-sump/csv/waterlevel-20170319.csv'
pi@sump:~/raspi-sump $

**Comment by alaudet** [comment]
You shouldn't have to run rsump.py with sudo.  When you run rsump.py the sensor takes a reading and logs it to waterlevel-20170319.csv  (which is today's date).  That is the problem we need to troubleshoot.  Don't bother running the rsumpchart.py if there is no csv file in ~/raspi-sump/csv folder.  You will always get FileNotFoundError.

The issue is trying to figure out why it's not taking the readings.  It can be any number of things.

Start from the beginning and lets look at your raspisump.conf file.  Is everything set right in there such as the gpio pins, pit_depth and critical_waterlevel.

**Comment by alaudet** [comment]
I am closing this issue as I have not heard back.  Will reopen if needed.
