### ISSUE TITLE
python3-matplotlib - does not work

### ISSUE THREAD

**Issue by spankurmonkey** [alaudet/raspi-sump#26]
pi@raspberrypi:~/raspi-sump $ sudo apt-get install python3-matplotlib
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package python3-matplotlib is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-matplotlib' has no installation candidate

**Comment by alaudet** [comment]
What Raspbian version are you running?

**Comment by spankurmonkey** [comment]
when I try to run it I get this:  
pi@raspberrypi:~/raspi-sump/logs $ rsump.py &
[1] 1058
pi@raspberrypi:~/raspi-sump/logs $ Traceback (most recent call last):
  File "/usr/local/bin/rsump.py", line 27, in <module>
    reading.water_depth()
  File "/usr/local/lib/python3.5/dist-packages/raspisump/reading.py", line 70, in water_depth
    log.log_reading(water_depth)
  File "/usr/local/lib/python3.5/dist-packages/raspisump/log.py", line 19, in log_reading
    csv_file = open(filename, 'a')
PermissionError: [Errno 13] Permission denied: '/home/pi/raspi-sump/csv/waterlevel-20180417.csv'

**Comment by alaudet** [comment]
Sorry I have been very busy in my personal life lately and have not had much chance to look at anything. 
The error is saying that there is a permission error in the csv folder.  Are there any files at all in that folder?

Do you even have a csv folder?

ls -al /home/pi/raspi-sump     
ls -al /home/pi/raspi-sump/csv

I would like to see the contents of these folders, If you can run these two commands that would be helpful.

**Comment by spankurmonkey** [comment]
Thanks for helping.  Here is the results of those two queries.
pi@raspberrypi:~ $ ls -al /home/pi/raspi-sump
total 44
drwxr-xr-x  9 pi root 4096 Apr 17 22:26 .
drwxr-xr-x 18 pi pi   4096 Apr 17 22:17 ..
drwxr-xr-x  2 pi root 4096 Apr 17 18:37 charts
drwxr-xr-x  2 pi root 4096 Apr 17 18:37 cron
drwxr-xr-x  2 pi root 4096 Apr 19 00:01 csv
drwxr-xr-x  2 pi root 4096 Apr 17 18:37 docs
drwxr-xr-x  2 pi root 4096 Apr 17 20:32 logs
-rw-r--r--  1 pi root 4955 Apr 17 21:31 raspisump.conf
drwxr-xr-x  2 pi root 4096 Apr 17 18:38 sample_config
drwxr-xr-x  4 pi root 4096 Apr 17 18:37 web
pi@raspberrypi:~ $ ls -al /home/pi/raspi-sump/csv
total 44
drwxr-xr-x 2 pi   root  4096 Apr 19 00:01 .
drwxr-xr-x 9 pi   root  4096 Apr 17 22:26 ..
-rw-r--r-- 1 pi   root    80 Jan 23 00:19 README.md
-rw-r--r-- 1 root root   286 Apr 17 22:26 waterlevel-20180417.csv
-rw-r--r-- 1 pi   pi   14976 Apr 18 23:59 waterlevel-20180418.csv
-rw-r--r-- 1 pi   pi    8398 Apr 19 13:29 waterlevel-20180419.csv
pi@raspberrypi:~ $

**Comment by spankurmonkey** [comment]
I did open up the csv for today and this is the output in ssh.
00:01:05,7.3
00:02:05,7.5
00:03:05,7.5
00:04:05,7.5
00:06:05,7.5
00:07:05,7.5
00:08:05,7.3
00:09:05,7.3
00:11:05,7.4
00:12:05,7.4
00:13:05,7.4
00:14:05,7.6
00:16:06,7.4
00:17:05,7.6
00:18:05,7.6
00:19:05,7.6
00:21:05,7.8
00:22:05,7.8
00:23:05,7.8
00:24:05,7.6
00:26:05,7.8
00:27:05,7.8
00:28:05,7.5
00:29:06,7.6
00:31:05,7.6
00:32:06,7.5
00:33:05,7.6
00:34:05,7.6
00:36:05,7.5
00:37:05,7.5
00:38:05,7.5
00:39:05,7.5
00:41:05,7.6
00:42:05,7.7
00:43:05,7.6
00:44:05,7.7
00:46:05,7.6
00:47:05,7.9

But when I go to the IP for it the browser does not display a chart.  it only shows a broken image link.

**Comment by spankurmonkey** [comment]
The charts directory is empty.  only has readme.md

**Comment by spankurmonkey** [comment]
I reran these and it seems matplotlib and numpy is installed but get the above error

pi@raspberrypi:~ $ sudo apt-get install python3-matplotlib
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-matplotlib is already the newest version (2.0.0+dfsg1-2).
The following packages were automatically installed and are no longer required:
  librtimulib-dev librtimulib-utils librtimulib7 python-rtimulib
  python-sense-hat python3-rtimulib
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~ $ sudo apt-get install python3-numpy
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-numpy is already the newest version (1:1.12.1-3).
The following packages were automatically installed and are no longer required:
  librtimulib-dev librtimulib-utils librtimulib7 python-rtimulib
  python-sense-hat python3-rtimulib
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~ $

**Comment by tonymontgomery** [comment]
As a sanity check... can you do the following and post results?

$ python3
>>> import numpy as np
>>> print (np.__version__)
>>> print (np.__path__)

>>> import matplotlib as mat
>>> print (mat.__version__)
>>> print (mat.__path__)

------------------
For example, here are my results:
```
$ python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170124] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> print (np.__version__)
1.12.1
>>> print (np.__path__)
['/usr/lib/python3/dist-packages/numpy']
>>> 
>>> import matplotlib as mat
>>> print (mat.__version__)
2.0.0
>>> print (mat.__path__)
['/usr/lib/python3/dist-packages/matplotlib']
>>> 
```

**Comment by spankurmonkey** [comment]
pi@raspberrypi:~ $ python -V
Python 2.7.13

pi@raspberrypi:~ $ python -c "import numpy; print(numpy.version.version)"
1.12.1

I don't know the correct commands to get the other stuff.

**Comment by tonymontgomery** [comment]
Cool... so there is one difference with matplotlib version.
Please also post the results for "python" (instead of 'python3').

**Comment by spankurmonkey** [comment]
pi@raspberrypi:~ $ python
Python 2.7.13 (default, Nov 24 2017, 17:33:09)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import numpy as np
>>> print (np.__version__)
1.12.1
>>> print (np.__path__)
['/usr/lib/python2.7/dist-packages/numpy']
>>> import matplotlib as mat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named matplotlib
>>>

**Comment by spankurmonkey** [comment]
thanks - did all those step but the last errors out.

pi@raspberrypi:~ $ rm -rf /home/pi/.config/matplotlib
pi@raspberrypi:~ $ rm -rf /home/pi/.cache/matplotlib
pi@raspberrypi:~ $ sudo rm -rf /usr/local/lib/python3.5/dist-packages/matplotlibpi@raspberrypi:~ $ sudo apt-get install python3-matplotlib
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-matplotlib is already the newest version (2.0.0+dfsg1-2).
The following packages were automatically installed and are no longer required:
  librtimulib-dev librtimulib-utils librtimulib7 python-rtimulib
  python-sense-hat python3-rtimulib
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~ $ dir
Desktop    Downloads  Pictures  python_games  Templates
Documents  Music      Public    raspi-sump    Videos
pi@raspberrypi:~ $ cd raspi-sump
pi@raspberrypi:~/raspi-sump $ sudo python setup.py install
python: can't open file 'setup.py': [Errno 2] No such file or directory
pi@raspberrypi:~/raspi-sump $

**Comment by spankurmonkey** [comment]
Ok. I reran the chart rsumpchart.py and rebooted and now the chart shows.   the time is off but I think I fixed it so starting tomorrow I believe I will have accurate times with the reading levels.

**Comment by spankurmonkey** [comment]
the only thing that is throwing me off is the chart numbers. 
![image 1](https://user-images.githubusercontent.com/17863712/39008900-aa7604c4-43cf-11e8-94ad-619e76b53a6d.jpg)
It shows from 2 to 9 inches.   My sensor is 21" above the bottom of the pit.   so does this mean it's reading a fluctuation of 2 to 9 inches of water in the sump?

# Unit of measure.  You may choose to use metric or imperial measurements.
# The unit variable must be set as metric or imperial and is case sensitive.
# Any other setting will cause an error.
unit = imperial

# critical_water_level is the water level in the sump pit at which point an
# email alert should be triggered.
# If unit = metric then critical_water_level = centimeters
# If unit = imperial then critical_water_level = inches
critical_water_level = 12

# The pit_depth is the distance between the sensor and the bottom of the
# sump pit.
# Like critical_water_level, enter centimeters for metric and inches for
# imperial
pit_depth = 21

# rsump.py should be run with a cron job.  However cron is limited to
# 1 minute as its minimum interval. If you need to monitor the sump level
# more frequently you can set reading_interval to the desired time in seconds.
# Default is 0 meaning only one reading will occur and the program will exit.
# If set to 0 call the script with a cron job and select your interval there.
# If setting to a value other than 0 you should run rsumpmonitor.py from a cron
# job at a regularly interval to monitor the health of the rsump.py process.
# rsumpmonitor.py is part of the raspisump software.  See documentation for
# details.
reading_interval = 0

# The temperature variable will adjust the speed of sound to reflect
# the normal temperature of your basement.
# If unit = metric then enter the temperature in Degrees Celcius.
# If unit = imperial then enter the temperature in Degrees Fahrenheit.
temperature = 66

# Raspi-Sump can also be used in situations where you would want to check if
# the water_level is too low. Sump pits are concerned with high water levels
# but a drinking water cistern would require an alert when it is low.  For that
# reason you can set the following value to 'low'.  Leave this value as is unless
# you specifically want alerts when the water drops below a certain level.
alert_when = high

**Comment by tonymontgomery** [comment]
Good deal - it's working.
In your photo, I would ignore the readings at "2". You are most likely getting reading anomalies.
This could all be affected by sensor position, how much space for sensor to take reading, etc.

If you look at it, you know it didn't go from 2 inches back up to over "8" that quick.
I would say water level gets to around 8.5 inches and pump is kicking on... drains pit to approx 4 inches.

You may have to play with the position of sensor. Wait a day, check graph, move if needed, etc.
But overall I think it looks good. I have never got mine to look as clean as the author's graph. But I can tell it's working and that's all I care about.

Your real reading is something like this:

![reading](https://user-images.githubusercontent.com/2413250/39011406-58c3b0f8-43df-11e8-8f16-5cfe79c26d62.jpg)

**Comment by spankurmonkey** [comment]
Thanks for your help.... with the time correction it seems to be working as expected.  I just have the sensor taped over a hole that allows the power line for the pump to exit so not sure if it has a clear line of sight to the bottom.  I am not sure how wide the sensor reads so like you said may have to position it around.

I wish I could have gotten this installed without issue... not sure what I did wrong.

**Comment by alaudet** [comment]
Thank you tonymontgomery for stepping in and answering.  For the chart, ya it really looks like interference on the sensor.  But usually it will show a higher waterlevel when it picks up the floating ball or something else.  This can be mitigated by sinking a tube into the pit and placing your sensor over the tube which focuses the sonar down and doesn't pick up all kinds of other garbage in the pit.

Glad you got it doing and sorry I could not spend more time troubleshooting with you.

Is everything now resolved?

**Comment by spankurmonkey** [comment]
Al - yes it seems to be working fine..... can you tell me more about the tube your speaking about?
![image 2](https://user-images.githubusercontent.com/17863712/39058010-4e0ac358-4480-11e8-8b75-e105033df663.jpg)

**Comment by spankurmonkey** [comment]
So today I moved the sensor - now it has a direct line of sight to the pit and no obstructions.   Indoing so the sensor is now 18.5" from the bottom of the pit.... can I use 18.5 in the config or must it be a whole number?

**Comment by alaudet** [comment]
Needs to be an integer, so no decimals.
-------- Original message --------From: spankurmonkey <notifications@github.com> Date: 4/20/18  1:35 PM  (GMT-05:00) To: alaudet/raspi-sump <raspi-sump@noreply.github.com> Cc: Al Audet <alaudet@linuxnorth.org>, Comment <comment@noreply.github.com> Subject: Re: [alaudet/raspi-sump] python3-matplotlib - does not work (#26) 
So today I moved the sensor - now it has a direct line of sight to the pit and no obstructions.   Indoing so the sensor is now 18.5" from the bottom of the pit.... can I use 18.5 in the config or must it be a whole number?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/alaudet/raspi-sump","title":"alaudet/raspi-sump","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/alaudet/raspi-sump"}},"updates":{"snippets":[{"icon":"PERSON","message":"@spankurmonkey in #26: So today I moved the sensor - now it has a direct line of sight to the pit and no obstructions.   Indoing so the sensor is now 18.5\" from the bottom of the pit.... can I use 18.5 in the config or must it be a whole number?"}],"action":{"name":"View Issue","url":"https://github.com/alaudet/raspi-sump/issues/26#issuecomment-383168663"}}}

**Comment by spankurmonkey** [comment]
I changed it back to a integer -  question... if I use the tube will the artifact go away... here is my latest chart and this is with the sensor point down.. directly to water with no obstructions in the way.
![image 3](https://user-images.githubusercontent.com/17863712/39069201-ab183eda-44a4-11e8-9622-4eafab575469.jpg)

**Comment by alaudet** [comment]
Not sure what you mean by the artifact.  You should get a more sane line by cutting out interference.  But you will not really know until you try.  Just setup something temporary with any cylinder on hand to test.  I have never actually done this but have had other users who reported success.
-------- Original message --------From: spankurmonkey <notifications@github.com> Date: 4/20/18  3:11 PM  (GMT-05:00) To: alaudet/raspi-sump <raspi-sump@noreply.github.com> Cc: Al Audet <alaudet@linuxnorth.org>, Comment <comment@noreply.github.com> Subject: Re: [alaudet/raspi-sump] python3-matplotlib - does not work (#26) 
I changed it back to a integer -  question... if I use the tube will the artifact go away... here is my latest chart and this is with the sensor point down.. directly to water with no obstructions in the way.



—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/alaudet/raspi-sump","title":"alaudet/raspi-sump","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/alaudet/raspi-sump"}},"updates":{"snippets":[{"icon":"PERSON","message":"@spankurmonkey in #26: I changed it back to a integer -  question... if I use the tube will the artifact go away... here is my latest chart and this is with the sensor point down.. directly to water with no obstructions in the way.\r\n![image 3](https://user-images.githubusercontent.com/17863712/39069201-ab183eda-44a4-11e8-9622-4eafab575469.jpg)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/alaudet/raspi-sump/issues/26#issuecomment-383194146"}}}
