### ISSUE TITLE
Report request Pump Cyles

### ISSUE THREAD

**Issue by rescuemoe** [alaudet/raspi-sump#43]
Just a thought for stats: when the Graph gets calculated also calculate how many times the Pump Cycled and keep a running total for the day

**Comment by spankurmonkey** [comment]
@rescuemoe 
Not sure if you seen this option using ThingSpeak -

Raspi-Sump feed into ThingSpeak - tracking sump water level, number of sump cycles, minutes since last sump cycle and gallons discharged 

https://thingspeak.com/channels/737963

![ThingSpeakRaspiSumpDashboard](https://user-images.githubusercontent.com/17863712/57950316-8a35cb00-78ac-11e9-8a7b-b36750f1a18b.jpg)

**Comment by spankurmonkey** [comment]
@rescuemoe 

Also on my mobile too:
![ThingSpeakRaspiSumpDashboardMobileWidget](https://user-images.githubusercontent.com/17863712/57950468-f0bae900-78ac-11e9-89fa-61f846d47f61.jpg)

**Comment by rescuemoe** [comment]
Ya I would love to do this.
Are there any instructions on how to set this up?

**Comment by alaudet** [comment]
The reason I have not added it is because every pump is different. I have been using a local application that does this but its not consistent.  All I have are readings so I need to identify the pump cycling by when it records a series of readings that are decreasing in depth.

It all falls apart in the spring when my pump kicks off  a minute after emptying as the readings get messed up.

Would need a way to hook into the pump to see when it triggers but its really not something I have considered.
